import React from "react";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "700"], // Adding default weights
});

export const metadata: Metadata = {
  title: "Greeka Assesment by Umar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${poppins.variable} `}>
        
        <Header />
        <div className="max-w-screen-xl mx-auto p-2">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
